version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build App Code
          command: |
            cd project
            ls
            sudo touch .env 
            echo "export MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING" > .env
            ls
            npm install
            npm run build

  test:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Test App
          command: |
            sudo chown -R $USER:$USER /home/circleci/project
            whoami
            pwd
            ls
            sudo touch .env 
            echo "export MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING" > .env
            ls
            echo "--- .env file ---"
            sudo cat .env

            echo "export MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING" >> $BASH_ENV
            echo "export process.env.MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING" >> $BASH_ENV

            sudo npm install
            sudo npm install jest jest-cli ts-jest supertest typescript --global
            sudo npm run test
          environment:
            MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
            process.env.MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}

  scan:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Audit Dependencies
          command: |
            npm install
            npm audit fix --audit-level=critical --force

# workflows:
#   node-tests:
#     jobs:
#       - node/test

# - build
# requires: [build]

workflows:
  default:
    jobs:
      - test
      - scan:
          requires: [test]
